## Student Information
- 64130500114
- Arissara Sanyaboot
- Group 2

In [1]:
x=5

In [3]:
print(x)

5


## **Intro. Python for Math/DS**

- Basic data type in Python
- Vector/Matrix Operation
- Eigenvector/Eigenvalue + PCA + Eigenface

### Basic data types

#### List  

อยู่ระหว่าง [ ] คั่นด้วย ,

In [8]:
a=['apple','orange']
b=['banana']
a+b

['apple', 'orange', 'banana']

In [5]:
x = [1,2,3]
y = [4,5,6]

In [6]:
z=x+y

In [7]:
z = x + y
z

[1, 2, 3, 4, 5, 6]

In [11]:
z[1:2]

[2]

In [9]:
z[:3] # z[0:3]

[1, 2, 3]

In [12]:
z[:-2]

[1, 2, 3, 4]

In [13]:
x + y

[1, 2, 3, 4, 5, 6]

In [14]:
a = ['pen','apple','asd']
b = ['student']

In [15]:
a + b

['pen', 'apple', 'asd', 'student']

#### Tuples
- อยู่ระหว่าง ( ) คั่นด้วย , 
- ไม่สามารถเปลี่ยนค่าตัวแปลได้

In [25]:
s = (100,120)

In [26]:
s[0] = 150  #รันไม่ผ่าน เพราะ tuple เปลี่ยนค่าไม่ได้ 

TypeError: 'tuple' object does not support item assignment

In [21]:
#list
t = [100,120]
t[0] = 150 
t

[150, 120]

In [22]:
t

[150, 120]

#### Set

- อยู่ระหว่าง {}  คั่นด้วย ,

In [23]:
a = {1,2,3,3}

In [24]:
a

{1, 2, 3}

#### Dectionary 

- syntax  {'key1':val1, 'key2':value}

In [27]:
product1 = {'name':"pencil", 'price':25}

In [28]:
product1['name']

'pencil'

In [29]:
product1['price']

25

### Control Statement

In [30]:
numbers = [3,7,9]
for i in numbers:
    print(i)

3
7
9


In [31]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [32]:
a = 5
while a > 3:
    print('Hello')
    a = a-1

Hello
Hello


### Numpy

In [33]:
import numpy as np

#x = [1,2,3]
#y = [4,5,6]
#z = x+y

x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
z

array([5, 7, 9])

## Vector


$ x = \begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix},  
 y = \begin{bmatrix} 6 \\ 7 \\ 8 \\ 9 \end{bmatrix} $



In [34]:
import numpy as np

#vector
x = np.array([1,2,3,4])
y = np.array([6,7,8,9])
x + y

array([ 7,  9, 11, 13])

In [43]:
# Reshape x,y to be a column vector
x = x.reshape((-1, 1))
y = y.reshape((-1, 1))

In [45]:
x.shape

(4, 1)

In [46]:
x.reshape((-1,1))

array([[1],
       [2],
       [3],
       [4]])

In [47]:
y.shape

(4, 1)

In [48]:
np.linalg.norm(x)

5.477225575051661

In [36]:
# Calculate Euclidean norm
euclidean_norm_x = np.linalg.norm(x)
euclidean_norm_y = np.linalg.norm(y)

# Calculate Manhattan norm (L1 norm)
manhattan_norm_x = np.linalg.norm(x, ord=1)
manhattan_norm_y = np.linalg.norm(y, ord=1)

# Calculate infinity norm (L∞ norm)
infinity_norm_x = np.linalg.norm(x, ord=np.inf)
infinity_norm_y = np.linalg.norm(y, ord=np.inf)

print("Euclidean norm of x:", euclidean_norm_x)
print("Euclidean norm of y:", euclidean_norm_y)
print("Manhattan norm of x:", manhattan_norm_x)
print("Manhattan norm of y:", manhattan_norm_y)
print("Infinity norm of x:", infinity_norm_x)
print("Infinity norm of y:", infinity_norm_y)

Euclidean norm of x: 5.477225575051661
Euclidean norm of y: 15.165750888103101
Manhattan norm of x: 10.0
Manhattan norm of y: 30.0
Infinity norm of x: 4.0
Infinity norm of y: 9.0


**Example 1:**
Calculate the **Euclidean norm** (2-norm) of the vector $\mathbf{v} = \begin{bmatrix} 3 \\ -4 \\ 5 \end{bmatrix}$.

In [37]:
v = np.array([3,-4,5])
v = v.reshape((-1, 1))
np.linalg.norm(v)

7.0710678118654755

**Example 2:**
Find the **Manhattan norm** (1-norm) of the vector $\mathbf{u} = \begin{bmatrix} 2 \\ -1 \\ 3 \end{bmatrix}$.

In [49]:
u=np.array([2,-1,3])
u=u.reshape((-1,1))
np.linalg.norm(u,ord=1)

6.0

**Example 3:**
Calculate the **infinity norm** ($\infty$-norm) of the vector $\mathbf{w} = \begin{bmatrix} 1 \\ -7 \\ 4 \end{bmatrix}$.

In [51]:
w=np.array([1,-7,4])
w=u.reshape((-1,1))
np.linalg.norm(w,ord=np.inf)

3.0

**Example 4:**
Given two vectors $\mathbf{a} = \begin{bmatrix} 2 \\ 5 \end{bmatrix}$ and $\mathbf{b} = \begin{bmatrix} -3 \\ 1 \end{bmatrix}$, find the **Euclidean distance** between them.


In [54]:
a = np.array([2,5])
b = np.array([-3,1])
a = a.reshape((-1,1))
b = b.reshape((-1,1))

euclidean_distance = np.linalg.norm(a - b)
print("Euclidean distance between a and b:", euclidean_distance)

Euclidean distance between a and b: 6.4031242374328485


In [60]:
a = np.array([2,5]).reshape((-1,1))
b = np.array([-3,1]).reshape((-1,1))
np.linalg.norm(a-b)

6.4031242374328485

**Example 5:**
Compute the **Manhattan distance** between vectors 
 $\mathbf{p} = \begin{bmatrix} 1 \\ 0 \\ -2 \end{bmatrix}$ and $\mathbf{q} = \begin{bmatrix} -3 \\ 2 \\ 1 \end{bmatrix}$.

In [58]:
p = np.array([1,0,-2]).reshape((-1,1))
q = np.array([-3,2,1]).reshape((-1,1))
manhattan_distance = np.linalg.norm(p-q, ord=1)
print("Manhattan distance between p and q: ", manhattan_distance)

Manhattan distance between p and q:  9.0


**Example 6:**
Find the **Chebyshev distance** (maximum norm) between vectors $\mathbf{x} = \begin{bmatrix} 2 \\ -4 \\ 7 \end{bmatrix}$ and $\mathbf{y} = \begin{bmatrix} -1 \\ 6 \\ 3 \end{bmatrix}$.

In [61]:
x = np.array([2,-4,7]).reshape((-1,1))
y = np.array([-1,6,3]).reshape((-1,1))
chebyshev_distance = np.linalg.norm(x-y, ord=np.inf)
print("Chebyshev_distance between x and y: ", chebyshev_distance)

Chebyshev_distance between x and y:  10.0


### Unit vector

**Example 1:**
Find the unit vector in the direction of the vector $\mathbf{v} = \begin{bmatrix} 3 \\ -4 \\ 5 \end{bmatrix}$.

In [62]:
import numpy as np

v = np.array([3, -4, 5])
v = v.reshape((-1,1))

# Calculate the Euclidean norm of vector v
norm_v = np.linalg.norm(v)

# Calculate the unit vector in the direction of v
unit_vector = v / norm_v

print("Unit vector in the direction of v:\n", unit_vector)


Unit vector in the direction of v:
 [[ 0.42426407]
 [-0.56568542]
 [ 0.70710678]]


**Example 2:**
Define the unit vector in the direction of vector $\mathbf{v} = \begin{bmatrix} 3 \\ -4 \\ 0 \end{bmatrix}$. 


In [64]:
v = np.array([3,-4,0]).reshape((-1,1))
norm_v = np.linalg.norm(v)
unit_vector = v/norm_v
print("Unit vector in the direction of v:\n",unit_vector)

Unit vector in the direction of v:
 [[ 0.6]
 [-0.8]
 [ 0. ]]


### Dot product

**Example:** 

$ \mathbf{u} = 
\begin{bmatrix}
1 \\2 \\ 3
\end{bmatrix},
\mathbf{v} = 
\begin{bmatrix}
4 \\ 5 \\ 6
\end{bmatrix} $

$ \langle\mathbf{u}, \mathbf{v}\rangle = \mathbf{u}\cdot \mathbf{v} = ? $

In [66]:
import numpy as np
u = np.array([1,2,3])
v = np.array([4, 5, 6])

#dot_product = np.dot(u, v)
#np.matmul(u,v)

dot_product = u@v
print("Dot product of u and v:", dot_product)

Dot product of u and v: 32


In [68]:
import numpy as np
u = np.array([1,2,3])
v = np.array([4,5,6])
u = u.reshape((-1,1))
v = v.reshape((-1,1))

#dot_product = np.dot(u.T, v)
dot_product = u.T@v
print("Dot product of u and v:", dot_product)

Dot product of u and v: [[32]]


**Example:** 
Given $ \mathbf{a} = \begin{bmatrix} 2 \\ -1 \\ 0 \end{bmatrix}, \mathbf{b} = \begin{bmatrix} 1 \\ 2 \\ 4 \end{bmatrix} $. Check whether a and b are orthogonal.

In [69]:
import numpy as np
u = np.array([2,-1,0])
v = np.array([1, 2, 4])
u = u.reshape((-1,1))
v = v.reshape((-1,1))

#dot_product = np.dot(u.T, v)
dot_product = u.T@v
print("Dot product of u and v:", dot_product)

Dot product of u and v: [[0]]


Ans: The dot product of the vectors **a** and **b**  is 0. Thus, they are orthogonal.

**Problem 8:**
Given vectors $\mathbf{p} = \begin{bmatrix} 2 \\ -1 \\ 3 \end{bmatrix}$ and $\mathbf{q} = \begin{bmatrix} 1 \\ 1 \\ 2 \end{bmatrix}$, find
the projection of $\mathbf{p}$ onto $\mathbf{q}$.

In [70]:
import numpy as np

p = np.array([2, -1, 3])
q = np.array([1, 1, 2])

# Calculate the dot product of p and q
dot_product = np.dot(p, q)

# Calculate the squared Euclidean norm of q
norm_squared = np.linalg.norm(q) ** 2

# Calculate the projection of p onto q
projection = (dot_product / norm_squared) * q

print("Projection of p onto q:", projection)

Projection of p onto q: [1.16666667 1.16666667 2.33333333]


**Problem 9:**
Find the projection of vector $\mathbf{x} = \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix}$ onto the vector $\mathbf{y} = \begin{bmatrix} 2 \\ 1 \\ 2 \end{bmatrix}$.

In [71]:
import numpy as np

p = np.array([1, 0, -1])
q = np.array([2, 1, 2])

# Calculate the dot product of p and q
dot_product = np.dot(p, q)

# Calculate the squared Euclidean norm of q
norm_squared = np.linalg.norm(q) ** 2

# Calculate the projection of p onto q
projection = (dot_product / norm_squared) * q

print("Projection of p onto q:", projection)

Projection of p onto q: [0. 0. 0.]


**Problem 10:**
Find the projection of vector $\mathbf{u} = \begin{bmatrix} 4 \\ -3 \\ 1 \end{bmatrix}$ onto the vector $\mathbf{v} = \begin{bmatrix} 1 \\ 2 \\ -2 \end{bmatrix}$.

In [72]:
import numpy as np

p = np.array([4, -3, 1])
q = np.array([1, 2, -2])

# Calculate the dot product of p and q
dot_product = np.dot(p, q)

# Calculate the squared Euclidean norm of q
norm_squared = np.linalg.norm(q) ** 2

# Calculate the projection of p onto q
projection = (dot_product / norm_squared) * q

print("Projection of p onto q:", projection)

Projection of p onto q: [-0.44444444 -0.88888889  0.88888889]


## Matrix


$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix},     
B = \begin{bmatrix}
10 & 20 & 30 \\
11 & 12 & 13 \\
\end{bmatrix}
$



In [73]:
#Matrix 

A = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9] ])
B = np.array([[10,20,30],
              [11,12,13] ])

In [74]:
A.shape

(3, 3)

In [75]:
print('Matrix A:\n', A)
print('Matrix B:\n', B)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[10 20 30]
 [11 12 13]]


In [76]:
#B*A
B@A

array([[300, 360, 420],
       [150, 186, 222]])

In [77]:
A@B.T

array([[140,  74],
       [320, 182],
       [500, 290]])

In [78]:
A[0,:] = [5,2,1]
A

array([[5, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

### Inverse and Determinant

In [80]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A[0,:] = [5,2,1]

# Calculate the inverse of matrix A
inverse_A = np.linalg.inv(A)

# Calculate the determinant of matrix A
det_A = np.linalg.det(A)

print("Inverse of A:")
print(inverse_A)

print("Determinant of A:", det_A)


Inverse of A:
[[ 0.5         1.66666667 -1.16666667]
 [-1.         -6.33333333  4.33333333]
 [ 0.5         4.33333333 -2.83333333]]
Determinant of A: -6.0


### Identity Matrix

In [81]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix_3x3 = np.identity(3)

# Create a 4x4 identity matrix
identity_matrix_4x4 = np.identity(4)
# identity_matrix_4x4 = np.eye(4)

print("3x3 Identity Matrix:")
print(identity_matrix_3x3)

print("4x4 Identity Matrix:")
print(identity_matrix_4x4)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Solve Linear Eqs. Sys.

$\begin{align*}
2x - 3y &= 5 \\
x + 2y &= -3 
\end{align*}$

In [83]:
import numpy as np

# Coefficients matrix
A = np.array([[2, -3],
              [1, 2]])

# Constants vector
B = np.array([5, -3])

# Solve the system of equations
inverse_A = np.linalg.inv(A)
solution = inverse_A@B

solution = np.linalg.solve(A, B)

print("Solution:")
print("x =", solution[0])
print("y =", solution[1])


Solution:
x = 0.1428571428571429
y = -1.5714285714285714


**Exercise 7.** Solve for \(x\), \(y\), and \(z\):

$\begin{align*}
x + y + z &= 6 \\
2y + 5z &= -4 \\
2x + 5y - z &= 27
\end{align*}$

In [84]:
import numpy as np

A = np.array([[1,1,1],
              [0,2,5],
              [2,5,-1]])

B = np.array([6,-4,27])

# Solve the system of equations
inverse_A = np.linalg.inv(A)
solution = inverse_A@B

solution = np.linalg.solve(A, B)

print("Solution:")
print("x =", solution[0])
print("y =", solution[1])
print("y =", solution[2])

Solution:
x = 5.0
y = 3.0
y = -2.0


**Exercise 8**. Solve the system of equations

$\begin{align*}
3x - y + 2z &= 1 \\
2x + y - z &= 4 \\
x + y + z &= 3 \\
\end{align*}$


In [85]:
import numpy as np

A = np.array([[3,-1,2],
              [2,1,-1],
              [1,1,1]])

B = np.array([1,4,3])

# Solve the system of equations
inverse_A = np.linalg.inv(A)
solution = inverse_A@B

solution = np.linalg.solve(A, B)

print("Solution:")
print("x =", solution[0])
print("y =", solution[1])
print("y =", solution[2])

Solution:
x = 1.0000000000000002
y = 2.0
y = -1.884014829666932e-16


**Exercise 10.** Find inverse of coefficient matrix and solve the following two equation systems: 

Solve for \( x \), \( y \), \( z \), and \( w \):

$\begin{align*}
x + y + z + w &= 10 \\
2x - y + 2z - w &= 3 \\
x + 2y - 3z + w &= 4 \\
3x - y + z - 2w &= 2 \\
\end{align*}$

Solve for \( x \), \( y \), \( z \), and \( w \):

$\begin{align*}
x + y + z + w &= 5 \\
2x - y + 2z - w &= 1 \\
x + 2y - 3z + w &= 2 \\
3x - y + z - 2w &= 0 \\
\end{align*}$

In [87]:
import numpy as np

A = np.array([[1,1,1,1],
              [2,-1,2,-1],
              [1,2,-3,1],[3,-1,1,-2]])

B = np.array([10,3,4,2])
C = np.array([5,1,2,0])

# Solve the system of equations
inverse_A = np.linalg.inv(A)
solutionA = inverse_A@B
solutionA = np.linalg.solve(A, B)

solutionB = inverse_A@C
solotionB = np.linalg.solve(A,C)

print("SolutionA:")
print("xA =", solutionA[0])
print("yA =", solutionA[1])
print("zA =", solutionA[2])

print("SolutionB:")
print("xB =", solutionB[0])
print("yB =", solutionB[1])
print("zB =", solutionB[2])

SolutionA:
xA = 1.166666666666667
yA = 6.666666666666666
zA = 3.166666666666667
SolutionB:
xB = 0.5000000000000002
yB = 3.0000000000000004
zB = 1.5000000000000004


## Eigenvector & Eigenvalue

In [88]:
import numpy as np

# Define the matrix A
# A = np.array([[3, 0],  #no inverse
#               [8, -1]])

A = np.array([[-1, 3],
              [2, 0]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues: [-3.  2.]
Eigenvectors:
[[-0.83205029 -0.70710678]
 [ 0.5547002  -0.70710678]]


In [89]:
 np.linalg.norm(eigenvectors[:,1])

0.9999999999999999

In [6]:
import numpy as np

# Original matrix A
A = np.array([[-1, 3],
              [2, 0]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Diagonal matrix L
L = np.diag(eigenvalues)

# Reconstructed matrix
reconstructed_matrix = eigenvectors @ L @ np.linalg.inv(eigenvectors)

# Check if the reconstructed matrix is approximately equal to the original matrix A
print("Is reconstructed matrix close to original matrix A:",
      np.allclose(A, reconstructed_matrix))

print("A:\n", A)
print("Reconstructed_matrix:\n", reconstructed_matrix)

Is reconstructed matrix close to original matrix A: True
A:
 [[-1  3]
 [ 2  0]]
Reconstructed_matrix:
 [[-1.00000000e+00  3.00000000e+00]
 [ 2.00000000e+00 -7.41483138e-17]]


## Eigenface

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_olivetti_faces
# from scipy.linalg import eig

# Load the Olivetti Faces dataset
faces_data = fetch_olivetti_faces(shuffle=True, random_state=42)

# Extract the image data from the dataset
X = faces_data.data

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to C:\Users\DELL\scikit_learn_data


HTTPError: HTTP Error 403: Forbidden

In [4]:
X.shape

NameError: name 'X' is not defined

In [5]:

plt.imshow(X[0].reshape(64, 64), cmap='gray')


NameError: name 'X' is not defined

In [5]:
# Calculate the covariance matrix
cov_matrix = np.cov(X.T)  # Transpose X to get variables as rows and observations as columns

NameError: name 'X' is not defined

In [4]:
cov_matrix.shape

NameError: name 'cov_matrix' is not defined

In [3]:
# Find the eigenvalues and eigenvectors
# eigenvalues, eigenvectors = eig(cov_matrix)
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)


NameError: name 'cov_matrix' is not defined

In [2]:
eigenvalues[:5]

NameError: name 'eigenvalues' is not defined

In [ ]:
# Use the top 5 eigenvalues and eigenvectors to transform the data
num_eigenfaces = 5
eigenfaces = eigenvectors[:, :num_eigenfaces]
transformed_data = np.dot(X, eigenfaces)


In [ ]:
eigenfaces.shape

In [ ]:
transformed_data.shape

In [ ]:
# Display the first original face
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
original_face = X[0].reshape(64, 64)
plt.imshow(original_face, cmap='gray')
plt.title("Original Face")

# Display the first face transformed by the top 5 eigenfaces
reconstructed_face = np.dot(transformed_data[0], eigenfaces.T)
reconstructed_face = reconstructed_face + np.mean(X, axis=0)  # Add back the mean
reconstructed_face = np.real(reconstructed_face)  # Convert to real numbers
plt.subplot(1, 2, 2)
plt.imshow(reconstructed_face.reshape(64, 64), cmap='gray')
plt.title("Transformed by Top 5 Eigenfaces")

plt.show()

*Tranformed 2D data*

In [6]:
# Use the top 2 eigenvalues/eigenvectors to transform the data
num_components = 2
top_eigenvectors = eigenvectors[:, :num_components]
transformed_data = np.dot(X, top_eigenvectors)

#  Plot the 2D data
plt.figure(figsize=(10, 6))
plt.scatter(transformed_data[:, 0], transformed_data[:, 1], c=faces_data.target, cmap='viridis')
plt.colorbar(label='Face ID')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA: 2D Visualization of Olivetti Faces')

# Add labels for each point with their target values
for i, txt in enumerate(faces_data.target):
    plt.text(np.real(transformed_data[i, 0]), np.real(transformed_data[i, 1]), str(txt), fontsize=10)


plt.show()

NameError: name 'eigenvectors' is not defined